/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;




import java.sql.*;
import model.Dal.ModuloConexaoJavastar;
import javax.swing.JOptionPane;


public class TelaLogin extends javax.swing.JFrame {
    
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public void logar(){
        String sql ="select*from tbusuarios where login=? and senha=?";
        try{
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtLoginLogin.getText());
            pst.setString(2, passLoginSenha.getText()); 
            rs = pst.executeQuery();
        if (rs.next()){
            TelaPrincipal principal = new TelaPrincipal();
            principal.setVisible(true);
        this.dispose(); //fechado a tela de login depois de logar
            conexao.close(); //fechado a tela de login depois de logar
        }else{
            JOptionPane.showMessageDialog(null,"Usuário ou senha invalido");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
            }
    }
        
    

   
        public TelaLogin() {
        initComponents();
        conexao = ModuloConexaoJavastar.conector(); 
    if (conexao != null){
    lblConexao.setText("Conectado");
    iconConexao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/certo.png")));
    painelConexao.add(iconConexao);
    
    }else{

    lblConexao.setText("Não Conectado");
    iconConexao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/errado.png")));
    painelConexao.add(iconConexao);

    }
    }

    
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLoginLogin = new javax.swing.JTextField();
        passLoginSenha = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        painelConexao = new javax.swing.JPanel();
        iconConexao = new javax.swing.JLabel();
        lblConexao = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Senha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 50, -1));

        txtLoginLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLoginLoginKeyPressed(evt);
            }
        });
        getContentPane().add(txtLoginLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 210, -1));

        passLoginSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passLoginSenhaActionPerformed(evt);
            }
        });
        passLoginSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passLoginSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(passLoginSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 210, -1));

        btnLogin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        btnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoginKeyPressed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 100, 40));

        iconConexao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconConexao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/errado.png"))); // NOI18N

        lblConexao.setText("Desconectado");

        javax.swing.GroupLayout painelConexaoLayout = new javax.swing.GroupLayout(painelConexao);
        painelConexao.setLayout(painelConexaoLayout);
        painelConexaoLayout.setHorizontalGroup(
            painelConexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConexaoLayout.createSequentialGroup()
                .addGroup(painelConexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConexaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconConexao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelConexaoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblConexao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelConexaoLayout.setVerticalGroup(
            painelConexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConexaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconConexao, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblConexao))
        );

        getContentPane().add(painelConexao, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 160));

        setSize(new java.awt.Dimension(404, 409));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        btnLogin.setToolTipText("Fazer Login");
        
        logar();
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void passLoginSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passLoginSenhaActionPerformed
        
        
    }//GEN-LAST:event_passLoginSenhaActionPerformed

    private void passLoginSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passLoginSenhaKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
          logar();       
        }
    }//GEN-LAST:event_passLoginSenhaKeyPressed

    private void btnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginKeyPressed
       
        if(evt.getKeyCode() == evt.VK_ENTER){
          logar();
        }
        
    }//GEN-LAST:event_btnLoginKeyPressed

    private void txtLoginLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginLoginKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
          passLoginSenha.requestFocus();
        }
    }//GEN-LAST:event_txtLoginLoginKeyPressed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel iconConexao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblConexao;
    private javax.swing.JPanel painelConexao;
    private javax.swing.JPasswordField passLoginSenha;
    private javax.swing.JTextField txtLoginLogin;
    // End of variables declaration//GEN-END:variables
}
